<?php

declare(strict_types=1);

$roomDescriptions = [
    'budget' => ['name' => "Sam's Suite", 'description' => "Welcome to our cozy budget room! For savvy travelers seeking a delightful stay without breaking the catnip bank, this snug space offers all the essentials for a comfortable catcation. Enjoy a purrfectly charming room filled with playful vibes and a touch of feline flair. Relax and recharge in this whisker-friendly hideaway, where frugal meets fabulous!", 'lore' => "This affordable room is named after Unsinkable Sam, the ship's cat who survived the sinking of three ships during World War II."],
    'standard' => ['name' => "Findus' Flat", 'description' => "Step into this delightful den designed for those seeking a little extra charm and comfort during their stay. It's a meowtel room filled with all the purrks you might desire, and features a blend of modern convenience and cozy cat-inspired details. Unwind in style and enjoy the playful ambiance that serves you the Cradle's essential blend of comfort and whimsy!", 'lore' => "This classic room is named after Findus, the beloved fun-loving feline known from Swedish children's literature. Complimentary pannkakstårta served on arrival."],
    'luxury' => ['name' => "Cheshire's Chamber", 'description' => "You are cordially invited to an unforgettable stay in our legendary premium suite, where opulence meets fun and fancy! Indulge in the lap of luxury in this regal space designed for the most discerning cat aficionados. From plush amenities to sophisticated décor, every detail exudes elegance and comfort. Immerse yourself in the ultimate cat-loving paradise, where every moment feels like a purrivilege!", 'lore' => "This pawsomely palacial place is named after the Cheshire Cat, of Wonderland fame - a playful trickster icon with a winning smile. Won't you stay for tea?"]
];
